#!/usr/bin/env ruby
#^syntax detection

forge 'http://forge.puppetlabs.com'

# modules from the Puppet Forge
mod 'erwbgy/limits'
mod 'hajee/easy_type'
mod 'biemond/oradb', '1.0.32'
mod 'hajee/oracle'

